### ISSUE TITLE
Could you release the 50k original architectures and their corresponding trained performance?

### ISSUE THREAD

**Issue by auroua** [automl/nasbench301#1]

**Comment by JulienSiems** [comment]
Hi @auroua 

We are planning to release them in collaboration with the Open Graph Benchmark and will update the repo once the dataset is available.

Best,
Julien

**Comment by auroua** [comment]
@JulienSiems 
Thanks for your reply!

**Comment by auroua** [comment]
Is there any plan to release the 50k trained architectures?
