### ISSUE TITLE
PyPi version does not seem to work (v0.2)

### ISSUE THREAD

**Issue by eddiebergman** [automl/nasbench301#10]
The PyPi version does not seem to include most of the source code.

This can be confirmed by going to PyPi, looking up `nasbench301`, download files and then downloading and viewing the tar ball.
* https://pypi.org/project/nasbench301/#files

I can also confirm it happens locally:
```bash
> mkdir ~/test

> cd test

> python -m venv ./.myvenv

> source ./.myvenv/bin/activate

> pip install --no-cache-dir nasbench301
Collecting nasbench301
  Downloading nasbench301-0.2-py3-none-any.whl (9.7 kB)
Installing collected packages: nasbench301
Successfully installed nasbench301-0.2

> ls .myvenv/lib/python3.8/site-packages/nasbench301
__pycache__  .  ..  api.py  example.py  __init__.py  representations.py

> python -c "import nasbench301"        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/eddiebergman/test/.myvenv/lib/python3.8/site-packages/nasbench301/__init__.py", line 1, in <module>
    from nasbench301.api import load_ensemble
  File "/home/eddiebergman/test/.myvenv/lib/python3.8/site-packages/nasbench301/api.py", line 6, in <module>
    from surrogate_models import utils
ModuleNotFoundError: No module named 'surrogate_models'
```

There are only the 4 files located in the installed package.

Unfortunately I have not actually released a package to PyPi so I am not sure of the fix but I would imagine it is a relatively straight forward issue to do with the `setup.py` file.

**Comment by arberzela** [comment]
Hi Eddie,

We updated the PyPi files to nasbench301-0.3 now and after installing all the necessary dependencies from `requirements.txt` there should not be any errors.

Cheers,
Arber
